# Generated by Django 6.0.5 on 2026-06-03 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0002_dietetic_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paciente_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="current_weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="goal",
            field=models.CharField(default="Salud integral", max_length=200),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="height_cm",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
