# Generated by Django 6.0.5 on 2026-06-03 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0003_paciente_user_alter_paciente_age_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nutricionista",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutricionista_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
