# Generated by Django 6.0.5 on 2026-06-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0004_nutricionista_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultadietetica",
            name="nutricionista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="dietetic.nutricionista",
            ),
        ),
        migrations.AlterField(
            model_name="consultadietetica",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="dietetic.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="consultadietetica",
            name="plan_nutricional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="dietetic.plannutricional",
            ),
        ),
    ]
