# Generated by Django 6.0.5 on 2026-06-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0005_alter_consultadietetica_nutricionista_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="full_name",
        ),
        migrations.AddField(
            model_name="paciente",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="paciente",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
