# Generated by Django 6.0.5 on 2026-06-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0006_remove_paciente_full_name_paciente_first_name_and_more"),
    ]

    operations = []
