# Generated by Django 6.0.5 on 2026-06-27 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0006_remove_paciente_full_name_paciente_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('MEDIA_MANANA', 'Media Mañana'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('SNACK', 'Snack')], max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Momento de comida',
                'verbose_name_plural': 'Momentos de comida',
                'db_table': 'momento_comida',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='consultadietetica',
            name='nutricionista',
        ),
        migrations.RemoveField(
            model_name='consultadietetica',
            name='paciente',
        ),
        migrations.CreateModel(
            name='DetallePlanAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alimento_programado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_plan', to='dietetic.alimentoprogramado')),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_alimentos', to='dietetic.plannutricional')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_plan', to='dietetic.plannutricional')),
            ],
            options={
                'verbose_name': 'Día del Plan',
                'verbose_name_plural': 'Días del Plan',
                'ordering': ['id'],
                'unique_together': {('plan_nutricional', 'dia_semana')},
            },
        ),
    ]
