# Generated by Django 6.0.5 on 2026-06-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0010_facturapago_delete_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanalimento',
            name='alimento_programado',
        ),
        migrations.RemoveField(
            model_name='detalleplanalimento',
            name='plan_nutricional',
        ),
        migrations.AlterUniqueTogether(
            name='diaplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='diaplan',
            name='plan_nutricional',
        ),
        migrations.RemoveField(
            model_name='facturapago',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='facturapago',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='MomentoComida',
        ),
        migrations.DeleteModel(
            name='DetallePlanAlimento',
        ),
        migrations.DeleteModel(
            name='DiaPlan',
        ),
        migrations.DeleteModel(
            name='FacturaPago',
        ),
    ]
