# Generated by Django 6.0.5 on 2026-06-27 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0011_remove_detalleplanalimento_alimento_programado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_plan', to='dietetic.plannutricional')),
            ],
            options={
                'verbose_name': 'Día del Plan',
                'verbose_name_plural': 'Días del Plan',
                'ordering': ['id'],
                'unique_together': {('plan_nutricional', 'dia_semana')},
            },
        ),
    ]
