# Generated by Django 6.0.5 on 2026-06-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0012_diaplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('MEDIA_MANANA', 'Media Mañana'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('SNACK', 'Snack')], max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Momento de comida',
                'verbose_name_plural': 'Momentos de comida',
                'db_table': 'momento_comida',
                'ordering': ['id'],
            },
        ),
    ]
