# Generated by Django 6.0.5 on 2026-06-27 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0013_momentocomida'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alimento_programado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_plan', to='dietetic.alimentoprogramado')),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_alimentos', to='dietetic.plannutricional')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
