# Generated by Django 6.0.5 on 2026-06-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0015_facturapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultadietetica',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='dietetic.nutricionista'),
        ),
        migrations.AddField(
            model_name='consultadietetica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='dietetic.paciente'),
        ),
    ]
