# Generated by Django 6.0.5 on 2026-06-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietetic', '0016_consultadietetica_nutricionista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_rutina', models.TextField()),
                ('dias_semana', models.CharField(max_length=100)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_ejercicio', to='dietetic.plannutricional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ejercicio', to='dietetic.paciente')),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='dietetic.rutinaejercicio')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('paciente', 'rutina_ejercicio', 'fecha')},
            },
        ),
    ]
