# dietetic/serializers/__init__.py
from .auth import CustomTokenSerializer
from .plan_nutricional import PlanNutricionalSerializer
from .alimento_programado import AlimentoProgramadoSerializer, AlimentoResumenSerializer
from .paciente import PacienteSerializer, SeguimientoNutricionalSerializer
from .nutricionista import NutricionistaSerializer
from .consulta_dietetica import ConsultaDieteticaSerializer
from .diaplan import DiaPlanSerializer
from .user import UserSerializer, RegisterSerializer
from .momento_comida import MomentoComidaSerializer
from .detalle_plan_alimento import DetallePlanAlimentoSerializer, DetallePlanAlimentoResumenSerializer
from .factura_pagos import FacturaPagoSerializer